// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetMissingDLC():Promise<string>;

export function GetMissingGames():Promise<Array<main.SwitchTitle>>;

export function GetMissingUpdates():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadSettings():Promise<string>;

export function OrganizeLibrary():Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function Start():Promise<void>;

export function UpdateDB():Promise<void>;

export function UpdateLocalLibrary(arg1:boolean):Promise<string>;

export function UpdateProgress(arg1:number,arg2:number,arg3:string):Promise<void>;
